GET http://localhost:3003/api/blog

###
GET http://localhost:3003/api/blog/667e14e20f71d5c4b116f973

###
POST http://localhost:3003/api/blog
Content-Type: application/json

{
    "title": "How could it be so hard?",
    "author":"Abraham P. N.",
    "url":"https://nothingnothing.com",
    "likes":100
}


