GET http://localhost:3003/api/blog

###
GET http://localhost:3003/api/blog/667e14e20f71d5c4b116f973

###
POST http://localhost:3003/api/blog
Content-Type: application/json

{
    "title": "Nothing",
    "author":"Abraham",
    "url":"https://nothing.com",
    "likes":400
}


